# Generated by Django 3.2 on 2023-04-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(null=True, verbose_name='Код-подтверждения'),
        ),
    ]
