# Generated by Django 3.2 on 2023-04-18 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230418_0618'),
        ('api', '0004_alter_title_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='titlegenre',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='titlegenre',
            name='title',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.DeleteModel(
            name='TitleGenre',
        ),
    ]
